// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WebsitesColumns holds the columns for the "websites" table.
	WebsitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "file_path", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "bright", Type: field.TypeFloat64},
		{Name: "flashy", Type: field.TypeFloat64},
		{Name: "adult", Type: field.TypeFloat64},
		{Name: "smart", Type: field.TypeFloat64},
		{Name: "beautiful", Type: field.TypeFloat64},
		{Name: "like", Type: field.TypeFloat64},
	}
	// WebsitesTable holds the schema information for the "websites" table.
	WebsitesTable = &schema.Table{
		Name:       "websites",
		Columns:    WebsitesColumns,
		PrimaryKey: []*schema.Column{WebsitesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		WebsitesTable,
	}
)

func init() {
}
